### ISSUE TITLE
Typo in profextract

### ISSUE THREAD

**Issue by sdupourque** [domeckert/pyproffit#11]
https://github.com/domeckert/pyproffit/blob/a911845c9ed39b1e37e811b8573be2ccc5540f8c/pyproffit/profextract.py#L457

Isn't the square in the wrong place here? 

eprof[i] = np.sqrt(np.sum((img[id] / exposure[id] )** 2)) / nv / pixsize ** 2

**Comment by domeckert** [comment]
No the formula is correct. The variance of a Poisson number (here img[id]) is the Poisson number itself. Therefore only the denominator (exposure) needs to be squared.
