### ISSUE TITLE
stan_utility is incompatible with pystan3

### ISSUE THREAD

**Issue by henrysting** [domeckert/pyproffit#21]
Due to the incompatibly between the stan_utility(0.1.2) and the pystan (3.x), the test_script.py could not finish successfully now. A easy solution is keeping the tool work with pytstan 2 (e.g. 2.19.1.1, import pystan) rather than pystan 3 (import stan). Or else, the stan_utility has to be replaced or updated.

**Comment by domeckert** [comment]
Thanks for the report @henrysting . I hadn't noticed this upstream change. 

As a workaround, in the "requirements.txt" file you can replace "pystan" with "pystan<3.0", this should force installation of an older version of stan. On the longer term we definitely to align with the upstream changes.

**Comment by henrysting** [comment]
Sounds good ! I confirm that the release 0.7.0 works well with pystan 2.
