### ISSUE TITLE
Question concerning physical scales during power spectrum analysis 

### ISSUE THREAD

**Issue by ktrehaeven** [domeckert/pyproffit#25]
Hi. May I please ask for some clarification on something?

The amplitude plots of the power spectrum analysis are plotted with k on the x-axis, with units of kpc^-1. But in the code k is defined as ` self.k = 1. / np.sqrt(2. * np.pi ** 2) * np.divide(1., sckpc)`, where `sckpc` I believe is the physical scale in kpc. This is where get confused. To find the physical scale that k corresponds to, do I need to invert this equation and solve for sckpc? I.e the physical scale is **not** just 1/k but the filtering factor np.sqrt(2. * np.pi ** 2) needs to be accounted for. Is this right?

I apologize for the very basic question - I just cant convince myself of the logic either way :)

**Comment by domeckert** [comment]
Hello @ktrehaeven . This is Eq. A5 of Arevalo et al. 2012 :

https://ui.adsabs.harvard.edu/abs/2012MNRAS.426.1793A/abstract

This equation relates the standard deviation of the Gaussian scale for the Mexican Hat filter to the wave number. Here sckpc is the sigma of the Mexican Hat filter, not the actual filtering scale, which is still 1/k. See Fig. 2 of Arevalo et al. 2012.

**Comment by ktrehaeven** [comment]
Ok then something like k = 0.01 kpc^-1 does indeed translate to a physical scale of 100 kpc?

**Comment by domeckert** [comment]
Yes, that's right. But that doesn't correspond to the sigma of the Mexican Hat filter.
