### ISSUE TITLE
About gas density profiles in different directions

### ISSUE THREAD

**Issue by ktrehaeven** [domeckert/pyproffit#27]
Good day

I want to study the thermal gas density profile in a galaxy cluster along the preferential orientation of the radio halo, ie in the regions shown in the attachment - the colour map is the x-ray residual surface brightness after dividing out the best-fit double-beta-model. I dont see the functionality to restrict the density profile to arbitrary azimuth angles anywhere in the code right now (if it is there please point me to it!). So where would be the best place to start if I want to add this functionality myself?
![Screenshot from 2024-06-13 16-02-44](https://github.com/domeckert/pyproffit/assets/77777044/1db79d32-c535-4843-87fa-67f08ba13ed6)

**Comment by domeckert** [comment]
Hi @ktrehaeven . This functionality is already in place. When you create a "Deproject" object (https://pyproffit.readthedocs.io/en/latest/pyproffit.html#pyproffit.deproject.Deproject) , you need to pass a Profile object which can include either the surface brightness profile for the full azimuth or for a specific sector. 

Then if you want to compare the gas densities for two (or more) sectors you will need to create separate Deproject objects and pass different profiles to each of them, and then run the deprojection calculation on each of them separately.

**Comment by ktrehaeven** [comment]
Ah I see...In the profextract.py script I didn't realize there were `angle_low` and `angle_high` options for extraction, ie...

`def SBprofile(self, ellipse_ratio=1.0, rotation_angle=0.0, angle_low=0., angle_high=360., minexp=0.05, box=False, width=None):`

Thanks very much!
