### ISSUE TITLE
dimensions of rkpc and dens does not match

### ISSUE THREAD

**Issue by henrysting** [domeckert/pyproffit#4]
Hi Domeckert, Thanks for bringing this powerful tool to Python !
Several tests fail when running the test_script.py:
1,  deproject.py
Line 50, 695, 696:  rkpc and dens/dens_lo/dens_hi  do not have same dimension, but have shapes (100,) and (50,)

2, deproject.py
Line 958, 1025,   calc_density_operator  takes 3 positional arguments but 4 were given

3, test_script.py
Line 170, the dimensions of dnh['DENSITY'] and depr.dens do not match, (100,) and (50,)

**Comment by domeckert** [comment]
Thanks for the bug report, I'm looking into it.

**Comment by domeckert** [comment]
Hi @henrysting  , I have just pushed a version which as far as I can see, fixes these bugs. Can you pull it and try again?

**Comment by henrysting** [comment]
Hi @domeckert , yes, they are fixed.
There are only two small bugs left in the test script now:
1, depr.Density()  is duplicated at lines 153 and 157
2, depr_stan.Density()  seems necessary before plot_multi_methods(line: 249)

**Comment by domeckert** [comment]
Thanks ! I'll close the issue
