### ISSUE TITLE
python3 test_script.py

### ISSUE THREAD

**Issue by monamolham** [domeckert/pyproffit#6]
Hi,
After Installation 
I run  test_script.py and I got the next error

~/validation$ python3.6 test_script.py
Traceback (most recent call last):
  File "test_script.py", line 58, in <module>
    prof.SBprofile(ellipse_ratio=ellrat,ellipse_angle=ellang+180.)
TypeError: SBprofile() got an unexpected keyword argument 'ellipse_angle'

According to the documentation, I replaced  "ellipse_angle" with "rotation_angle" and this step passed.
I thought it would be helpful to mention that!

**Comment by domeckert** [comment]
Thanks! Indeed, I changed the name of the parameter but forgot to update the test script.

**Comment by domeckert** [comment]
Pushed update, closing
